const recipes = [
  {
    name: "Peachy Fattoush",
    ingredients: [
      "lemon",
      "agave nector",
      "red wine vinegar",
      "olive oil",
      "basil",
      "mint",
      "parsley",
      "peach",
      "grape tomatoes",
      "sumac",
    ],
    source: "Eden Grinshpan",
  },
  {
    name: "Weeknight Salmon",
    ingredients: [
      "salmon",
      "baby potatoes",
      "olive oil",
      "lemon",
      "pepper",
      "parsley",
      "butter",
      "paprika",
    ],
    source: "Joanna Gaines",
  },
  {
    name: "Chickpea Masala",
    ingredients: [
      "butter",
      "onion",
      "garlic",
      "ginger",
      "cumin",
      "coriander",
      "tumeric",
      "paprika",
      "san marzano tomatoes",
      "chickpeas",
      "apricots",
      "basmati rice",
      "cilantro",
    ],
    source: "Antoni Porowski",
  },
  {
    name: "Shakshuka",
    ingredients: [
      "eggs",
      "san marzano tomatoes",
      "cumin",
      "onion",
      "red pepper",
      "tumeric",
    ],
    source: "Eden Grinshpan",
  },
  {
    name: "Red beans and rice ",
    ingredients: [
      "canned kidney beans",
      "bay leaf",
      "cayenne pepper",
      "black pepper",
      "celery",
      "bell pepper",
      "onion",
      "cajun season",
      "sausage",
      "rice",
    ],
    source: "Savoy Family",
  },
  {
    name: "Veggie Taco Salad",
    ingredients: [
      "romaine lettuce",
      "walnuts",
      "cauliflower",
      "taco seasoning",
      "salsa",
      "avocado",
      "jalapeno",
    ],
    source: "Pinch of Yum",
  },
  {
    name: "Salmon Teriyaki bowls ",
    ingredients: [
      "salmon",
      "teriyaki sauce",
      "sushi rice",
      "brocoli",
      "hot sesame oil",
      "shallots",
      "furiake",
    ],
    source: "Khavoy",
  },
  {
    name: "Korean BBQ bowls",
    ingredients: [
      "prime rib",
      "sushi rice",
      "egg",
      "kale slaw",
      "mirin",
      "rice vinegar",
      "soy sauce",
      "ginger",
      "pear",
    ],
    source: "Pinch of Yum",
  },
  {
    name: "Tumeric cauliflower",
    ingredients: [
      "Cauliflower florets",
      "tumeric",
      "gojuchang",
      "lime",
      "cilantro",
      "olive oil",
      "basmati rice",
    ],
    source: "Antoni Porowski",
  },
  {
    name: "Veggie Shawarma Pita  ",
    ingredients: [
      "red peppers",
      "red onion",
      "chickpeas",
      "garlic",
      "shawarma seasoning",
      "pita bread",
      "grape tomatos",
      "parsley",
      "tahini",
    ],
    source: "Pinch of Yum",
  },
  {
    name: "Sweet potato/spinach/ egg bowl ",
    ingredients: [
      "sweet potato",
      "spinach",
      "quinoa",
      "avocado",
      "red chilis",
      "tahini ",
    ],
    source: "Pinch of Yum",
  },
  {
    name: "Peas and Rice ",
    ingredients: [
      "Frozen peas",
      "ground beef",
      "roma tomatoes",
      "onion",
      "cumin",
      "all spice",
      "sumac",
      "paprika",
      "salt",
      "basmati rice",
    ],
    source: "Savoy Family",
  },
  {
    name: "Turkey kefte and rice pilaf ",
    ingredients: [
      "Ground Turkey",
      "Mint",
      "olive oil ",
      "onion",
      "cumin",
      "aleppo peppers",
      "cinnamon",
      "pepper",
      "rice",
      "grape tomatoes",
      "red onion",
    ],
    source: "Antoni Porowski",
  },
  {
    name: "Strawberry Salad",
    ingredients: [
      "strawberries",
      "chickpeas",
      "mixed lettuce",
      "red onion",
      "avocado",
      "tahini",
      "mustard",
      "balsamic",
      "olive oil ",
    ],
    source: "Khavoy",
  },
  {
    name: "Avocado Toast",
    ingredients: ["bread", "avocado", "lime", "salt"],
    source: "Khavoy",
  },
  {
    name: "Madeira",
    ingredients: [
      "onion",
      "black lentils",
      "basmatie rice",
      "cumin",
      "tumeric",
      "tahini",
      "lemon",
      "grape tomatoes",
      "olive oil",
      "grapeseed oil",
      "shallots",
    ],
    source: "Eden Grinsphan",
  },
  {
    name: "Tamale casserole",
    ingredients: [
      "canned black beans",
      "canned kidney beans",
      "canned corn",
      "masa",
      "butter",
      "veggie broth",
      "chili seasoning",
      "cumin",
      "jalapeno",
    ],
    source: "Khavoy",
  },
  {
    name: "Asparagus, tomato pesto pasta",
    ingredients: ["asparagus", "pesto", "grape tomatoes", "bow tie Noodles"],
    source: "Khavoy",
  },
  {
    name: "Japanese egg and rice with spicy broccoli",
    ingredients: [
      "sushi rice",
      "egg",
      "brocoli",
      "furiake",
      "soy sauce",
      "sesame oil",
    ],
    source: "Breath of the Wild",
  },
  {
    name: "Tomato Toast",
    ingredients: ["tomato", "bread", "cream cheese", "balsamic"],
    source: "Khavoy",
  },
  {
    name: "Vegan Tofu Stir Fry",
    ingredients: [
      "Extra Firm Tofu",
      "Soy Sauce",
      "Sesame Oil",
      "Scallions",
      "Garlic",
      "Ginger",
      "Cornstarch",
      "Chili Garlic Sauce",
      "Zucchinis",
      "Red Bell Pepper",
      "Yellow Bell Pepper",
      "Onion",
      "White Rice",
    ],
    source: "Maxi's Kitchen",
  },
  {
    name: "Healthy Shrimp Tacos",
    ingredients: [
      "Large Shrimp",
      "Chili Powder",
      "Cumin",
      "Garlic Powder",
      "Flour or Corn Tortillas",
      "Avocado",
      "Cabbage",
      "Jalapeño",
      "Greek Yogurt",
      "Light Sour Cream",
      "Cilantro",
      "Limes",
    ],
    source: "Maxi's Kitchen",
  },
  {
    name: "Blackened Chicken",
    ingredients: [
      "Chicken Thighs",
      "Paprika",
      "Onion Powder",
      "Garlic Powder",
      "Oregano",
      "Thyme",
      "Cayenne Pepper",
      "Parsley",
    ],
    source: "Maxi's Kitchen",
  },
  {
    name: "Parmesan Crusted Chicken",
    ingredients: [
      "Boneless Skinless Chicken Breasts",
      "All Purpose Flour",
      "Eggs",
      "Grated Parmesan",
      "Italian Breadcrumbs",
      "Lemon Wedges",
      "Arugula",
      "Red Wine Vinegar",
    ],
    source: "Maxi's Kitchen",
  },
  {
    name: "Chicken Wontons in Spicy Chili Sauce",
    ingredients: [
      "Pre-made mini wontons",
      "Chili crisp",
      "Bean sprouts",
      "Broth",
      "Fried veggie rice",
    ],
    source: "Pinch of Yum",
  },
  {
    name: "Coconut Curry Salmon",
    ingredients: [
      "Salmon",
      "Coconut milk",
      "Red curry paste",
      "Lemongrass",
      "Spinach",
      "Fish sauce",
      "Brown sugar",
    ],
    source: "Pinch of Yum",
  },
];
